services:
  - type: web
    name: cfo-ai-backend
    runtime: node
    repo: https://github.com/tu-usuario/cfo-ai-backend
    buildCommand: npm install && npm run migrate && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        value: 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
      - key: LLM_PROVIDER
        value: openrouter
      - key: APP_URL
        value: https://cfo-ai-backend-4n29.onrender.com
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/database
      sizeGB: 1
